name: vagen
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.9.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.0
  - comm=0.2.3
  - dav1d=1.2.1
  - debugpy=1.8.16
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=6.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.2
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - lame=3.100
  - ld_impl_linux-64=2.44
  - libabseil=20240722.0
  - libass=0.17.3
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=5.28.2
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libva=2.22.0
  - libvpx=1.14.1
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.4.1
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - tbb=2022.3.0
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wcwidth=0.2.14
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - adam-atan2-pytorch==0.2.4
      - aeiou==0.0.21
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - alembic==1.17.0
      - alias-free-torch==0.0.6
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - argbind==0.3.9
      - argparse==1.4.0
      - asteroid-filterbanks==0.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.0.1
      - auraloss==0.4.0
      - av==16.0.1
      - banal==1.0.6
      - beartype==0.22.2
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - blis==1.3.3
      - bokeh==3.8.1
      - braceexpand==0.1.7
      - brotli==1.1.0
      - catalogue==2.0.10
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - clean-fid==0.1.35
      - click==8.3.0
      - clip-anytorch==2.6.0
      - cloudpathlib==0.23.0
      - colorcet==3.1.0
      - colorlog==6.10.1
      - confection==0.1.5
      - configparser==7.2.0
      - contourpy==1.3.2
      - cryptography==46.0.2
      - cycler==0.12.1
      - cymem==2.0.13
      - dashscope==1.24.6
      - datasets==4.2.0
      - dctorch==0.1.2
      - decorator==4.4.2
      - decord==0.6.0
      - descript-audio-codec==1.0.0
      - descript-audiotools==0.7.2
      - diffusers==0.32.1
      - dill==0.4.0
      - distance==0.1.3
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - einops-exts==0.0.4
      - einx==0.3.0
      - ema-pytorch==0.2.3
      - encodec==0.1.1
      - espnet-tts-frontend==0.0.3
      - et-xmlfile==2.0.0
      - fastapi==0.119.0
      - fastcore==1.8.17
      - ffmpeg-python==0.2.0
      - ffmpy==0.6.3
      - filelock==3.20.0
      - fire==0.7.1
      - flash-attn==2.8.3
      - flatten-dict==0.4.2
      - flow-matching==1.0.9
      - fonttools==4.60.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - g2p-en==2.1.0
      - gdown==5.2.0
      - gin-config==0.5.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.1
      - gradio-client==1.13.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.15.1
      - hangul-romanize==0.1.0
      - hf-xet==1.2.0
      - hl-gauss-pytorch==0.1.24
      - holoviews==1.22.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.0
      - humanfriendly==10.0
      - hyper-connections==0.2.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==5.12.0
      - inflect==7.5.0
      - jaconv==0.4.0
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonmerge==1.9.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - julius==0.2.7
      - k-diffusion==0.1.1
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning-utilities==0.15.2
      - linkify-it-py==2.0.3
      - llvmlite==0.45.1
      - local-attention==1.8.6
      - loguru==0.7.3
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - murmurhash==1.0.15
      - narwhals==2.13.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.25.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.6.0
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - optimum-quanto==0.2.7
      - orjson==3.11.3
      - pandas==2.0.2
      - panel==1.8.4
      - param==2.3.1
      - pathtools==0.1.2
      - pedalboard==0.9.19
      - peft==0.17.1
      - pillow==10.4.0
      - pillow-heif==1.1.1
      - plotly==6.5.0
      - pooch==1.8.2
      - prefigure==0.0.9
      - preshed==3.0.12
      - prodigyopt==1.1.2
      - proglog==0.1.12
      - progressbar==2.5
      - propcache==0.4.1
      - protobuf==3.19.6
      - py3langid==0.3.0
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyloudnorm==0.1.1
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pypinyin==0.55.0
      - pysocks==1.7.1
      - pystoi==0.4.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytorch-lightning==1.9.2
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - randomname==0.2.1
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - resampy==0.4.3
      - rich==14.2.0
      - rpds-py==0.30.0
      - ruff==0.14.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.41.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==1.4.54
      - srsly==2.5.2
      - starlette==0.48.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.20
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.6.0
      - torch-stoi==0.2.3
      - torchaudio==2.6.0
      - torchdiffeq==0.2.5
      - torchlibrosa==0.1.0
      - torchmetrics==0.11.4
      - torchsde==0.2.6
      - torchvision==0.21.0
      - tqdm==4.67.1
      - trampoline==0.1.2
      - transformers==4.57.1
      - triton==3.2.0
      - typeguard==4.4.4
      - typer==0.19.2
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - umap-learn==0.5.9.post2
      - unidecode==1.4.0
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - v-diffusion-pytorch==0.0.2
      - vector-quantize-pytorch==1.14.41
      - vocos==0.1.0
      - wadler-lindig==0.1.7
      - wandb==0.23.1
      - wasabi==1.1.3
      - weasel==0.4.3
      - webdataset==0.2.100
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wget==3.2
      - wrapt==2.0.1
      - x-transformers==2.10.0
      - xxhash==3.6.0
      - xyzservices==2025.11.0
      - yarl==1.22.0
prefix: /home/chengxin/anaconda3/envs/vagen
